name:                OSMRouter
version:             0.1.0.0
github:              "alephu5/OSMRouter"
license:             BSD3
author:              "Nigel Sotelo"
maintainer:          "morrison.sotelo@gmail.com"
copyright:           "GPL 3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alephu5/OSMRouter#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.6 && < 0.7
- errors >= 2.3 && < 2.4
- fgl >= 5.7 && < 5.8
- mtl >= 2.2 && < 2.3
- req >= 2.1 && < 2.2
- resourcet >= 1.2 && < 1.3
- streaming >= 0.2 && < 0.3
- streaming-osm
- xeno >= 0.3 && < 0.4


library:
  source-dirs: src
  # default-extensions:
  #   - OverloadedStrings
  #   - RecordWildCards

executables:
  OSMRouter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -fno-warn-type-defaults
    - -fwarn-unused-do-bind
    - -fwarn-unused-imports
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - OSMRouter

tests:
  OSMRouter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -fno-warn-type-defaults
    - -fwarn-unused-do-bind
    - -fwarn-unused-imports
    dependencies:
    - OSMRouter
